package com.suvojeet.notenext.ui.theme

import androidx.compose.ui.graphics.Color

// Light Scheme Tokens
val primaryLight = Color(0xFF3949AB)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE8EAF6)
val onPrimaryContainerLight = Color(0xFF1A237E)
val primaryFixedLight = Color(0xFFE8EAF6)
val primaryFixedDimLight = Color(0xFFC5CAE9)
val onPrimaryFixedLight = Color(0xFF1A237E)
val onPrimaryFixedVariantLight = Color(0xFF3949AB)

val secondaryLight = Color(0xFF5C6BC0)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE8EAF6)
val onSecondaryContainerLight = Color(0xFF1A237E)
val secondaryFixedLight = Color(0xFFE8EAF6)
val secondaryFixedDimLight = Color(0xFFC5CAE9)
val onSecondaryFixedLight = Color(0xFF1A237E)
val onSecondaryFixedVariantLight = Color(0xFF5C6BC0)

val tertiaryLight = Color(0xFF7D5260)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD8E4)
val onTertiaryContainerLight = Color(0xFF31111D)
val tertiaryFixedLight = Color(0xFFFFD8E4)
val tertiaryFixedDimLight = Color(0xFFEFB8C8)
val onTertiaryFixedLight = Color(0xFF31111D)
val onTertiaryFixedVariantLight = Color(0xFF7D5260)

val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)

val backgroundLight = Color(0xFFF9F9FF)
val onBackgroundLight = Color(0xFF1B1B21)
val surfaceLight = Color(0xFFF9F9FF)
val onSurfaceLight = Color(0xFF1B1B21)
val surfaceVariantLight = Color(0xFFE3E1EC)
val onSurfaceVariantLight = Color(0xFF46464F)

val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF3F3FA)
val surfaceContainerLight = Color(0xFFEDEDF4)
val surfaceContainerHighLight = Color(0xFFE7E7EE)
val surfaceContainerHighestLight = Color(0xFFE2E2E9)

val outlineLight = Color(0xFF777680)
val outlineVariantLight = Color(0xFFC7C5D0)
val scrimLight = Color(0xFF000000)
val shadowLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF303036)
val inverseOnSurfaceLight = Color(0xFFF1F0F7)
val inversePrimaryLight = Color(0xFFBCC2FF)

// Dark Scheme Tokens
val primaryDark = Color(0xFFBCC2FF)
val onPrimaryDark = Color(0xFF001469)
val primaryContainerDark = Color(0xFF1E3192)
val onPrimaryContainerDark = Color(0xFFE0E0FF)
val primaryFixedDark = Color(0xFFE8EAF6)
val primaryFixedDimDark = Color(0xFFC5CAE9)
val onPrimaryFixedDark = Color(0xFF1A237E)
val onPrimaryFixedVariantDark = Color(0xFF3949AB)

val secondaryDark = Color(0xFFC1C5FF)
val onSecondaryDark = Color(0xFF252B61)
val secondaryContainerDark = Color(0xFF3D4279)
val onSecondaryContainerDark = Color(0xFFE1E0FF)
val secondaryFixedDark = Color(0xFFE8EAF6)
val secondaryFixedDimDark = Color(0xFFC5CAE9)
val onSecondaryFixedDark = Color(0xFF1A237E)
val onSecondaryFixedVariantDark = Color(0xFF5C6BC0)

val tertiaryDark = Color(0xFFEFB8C8)
val onTertiaryDark = Color(0xFF492532)
val tertiaryContainerDark = Color(0xFF633B48)
val onTertiaryContainerDark = Color(0xFFFFD8E4)
val tertiaryFixedDark = Color(0xFFFFD8E4)
val tertiaryFixedDimDark = Color(0xFFEFB8C8)
val onTertiaryFixedDark = Color(0xFF31111D)
val onTertiaryFixedVariantDark = Color(0xFF7D5260)

val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)

val backgroundDark = Color(0xFF121318)
val onBackgroundDark = Color(0xFFE4E1E9)
val surfaceDark = Color(0xFF121318)
val onSurfaceDark = Color(0xFFE4E1E9)
val surfaceVariantDark = Color(0xFF46464F)
val onSurfaceVariantDark = Color(0xFFC7C5D0)

val surfaceContainerLowestDark = Color(0xFF0D0E13)
val surfaceContainerLowDark = Color(0xFF1B1B21)
val surfaceContainerDark = Color(0xFF1F1F25)
val surfaceContainerHighDark = Color(0xFF292A2F)
val surfaceContainerHighestDark = Color(0xFF34343A)

val outlineDark = Color(0xFF91909A)
val outlineVariantDark = Color(0xFF46464F)
val scrimDark = Color(0xFF000000)
val shadowDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE4E1E9)
val inverseOnSurfaceDark = Color(0xFF303036)
val inversePrimaryDark = Color(0xFF3949AB)
